# Generated by Django 5.0.6 on 2024-05-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(default='blankprofile.webp', upload_to='perfil'),
        ),
    ]
