# Generated by Django 5.0.6 on 2024-05-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg_app', '0002_alter_perfil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(default='perfil/blankprofile.webp', upload_to='perfil'),
        ),
    ]
